Atelier/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import (ClientView, DetailClient,
                    DelClient,DelTask, OrderView,MonthOrderView,TodoListView,SetTaskDone, TaskUpdateView, ServiceView,CustomLoginView,OrderSummary,SetPaidByDate, SetPaid,add_to_cart,UpdateService,DelService,HomeView,get_data,DetailOrder,DelOrder,remove_from_cart)
from django.contrib.auth.views import LogoutView


app_name = 'core'

urlpatterns = [
     path('panel/clientes/', ClientView.as_view(), name='clientes'),
     path('panel/clientes/<pk>/', DetailClient, name="detail_client"),
     path('del_client/<pk>/', DelClient, name="del_client"),
     path('panel/servicios/', ServiceView.as_view(), name='services'),
     path('panel/pedidos/', OrderView.as_view(), name='orders'),
     path('panel/pedidos/<pk>/', DetailOrder, name="detail-order"),
     path("panel/pedidos/<int:pk>/ispaid/", SetPaid,
          name='ispaid'),
     path('panel/nuevo_pedido/',OrderSummary.as_view(),name='summary'),
     path('add-to-cart/<int:pk>/', add_to_cart, name='add-to-cart'),
     path('remove_from_cart/<int:pk>/', remove_from_cart, name='remove-from-cart'),
     path('detail_service/<int:pk>/', UpdateService, name='detail_service'),
     path('delete_serv/<pk>/', DelService.as_view(), name='del-serv'),
     path('',HomeView.as_view(),name='home'),
     path('api/data/', get_data, name="feo"),
     path('del_order/<pk>/', DelOrder.as_view(), name='del-order'),
     path('panel/pedidos/<int:year>/<int:month>/',
          MonthOrderView.as_view(month_format='%m'),
          name="orders-month"),
     path("pedidos/<int:pk>/<int:year>/<int:month>/ispaidbydate/", SetPaidByDate,
          name='ispaidbydate'),
     path('login/', CustomLoginView.as_view(), name='login'),
     path('logout/', LogoutView.as_view(next_page='core:login'), name='logout'),
     path('panel/task/',TodoListView.as_view(),name='task'),
     path('panel/task/<pk>/',TaskUpdateView.as_view(),name='detail-task'),
     path("panel/task/<int:pk>/isdone/", SetTaskDone,
          name='isdone'),
     path('del_task/<pk>/', DelTask.as_view(), name='del-task'), 
]

templates/base.html
{% load static %} {% now "o" as current_y %} {% now "m" as current_m %} 

<!DOCTYPE html>
<html lang="es">

<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>{% block title %}{% endblock title %}</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
  <!-- MDB -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
  <!-- Custom styles -->
  <link rel="stylesheet" href="{% static 'css/admin.css' %}" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
    crossorigin="anonymous"></script>
     
</head>

<body>
  <section class="margin-top: 58px"> <div class="container"> {% block login %}{% endblock login %}</div></section>
  <!--Main Navigation-->
  {% if request.user.is_authenticated %}
  <header>
    
    <!-- Sidebar -->
    {% with request.resolver_match.url_name as url_name %}
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse bg-white">
      <div class="position-sticky">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a href="{% url 'core:home' %}" class="list-group-item list-group-item-action py-2 ripple {% if url_name == 'home' %}active{% endif %}" aria-current="true">
            <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Dashboard</span>
          </a>
          <a href="{% url 'core:services' %}" class="list-group-item list-group-item-action py-2 ripple {% if "/servicios/" in request.path %} active {% endif %}">
            <i class="fas fa-chart-area fa-fw me-3"></i><span>Servicios</span>
          </a>
          <a href="{% url 'core:clientes' %}" class="list-group-item list-group-item-action py-2 ripple {% if "/clientes/" in request.path %} active {% endif %}"><i
              class="fas fa-users fa-fw me-3"></i><span>Clientes</span></a>
          <a href="{% url 'core:orders' %}" class="list-group-item list-group-item-action py-2 ripple {% if url_name == 'orders' %}active{% endif %}"><i
              class="fas fa-chart-line fa-fw me-3"></i><span>Ordenes</span></a>
          <a href="{% url 'core:summary' %}" class="list-group-item list-group-item-action py-2 ripple {% if "/nuevo_pedido/" in request.path %} active {% endif %}">
            <i class="fas fa-chart-pie fa-fw me-3"></i><span>Nuevo pedido</span>
          </a>
         
          <a href="{% url 'core:orders-month' current_y current_m %}" class="list-group-item list-group-item-action py-2 ripple {% if url_name == 'orders-month' %}active{% endif %}"><i
              class="fas fa-calendar fa-fw me-3"></i><span>Este mes</span></a>
          
          <a href="{% url 'core:task' %}" class="list-group-item list-group-item-action py-2 ripple {% if url_name == 'task' %}active{% endif %}"><i
              class="fas fa-money-bill fa-fw me-3"></i><span>Tareas</span></a>
        </div>
      </div>
    </nav>
    {% endwith %}
    <!-- Sidebar -->
     <!-- Navbar -->
     <nav id="main-navbar" class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <!-- Container wrapper -->
      <div class="container-fluid">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#sidebarMenu"
          aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>

        <!-- Brand -->
        <a class="navbar-brand" href="#">
          
          <img src="https://img.icons8.com/dotty/50/000000/sewing-machine.png" height="40" alt="" loading="lazy"/>
        </a>
        <!-- Search form -->
        <form class="d-none d-md-flex input-group w-auto my-auto">
          <input autocomplete="off" type="search" name='search-area' class="form-control rounded"
            placeholder='' style="min-width: 225px" />
          <span class="input-group-text border-0"><i class="fas fa-search"></i></span>
        </form>

        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex flex-row">
          
          
          <!-- Icon -->
          <li class="nav-item me-3 me-lg-0">
            <a class="nav-link" href="https://github.com/Kubiniet/Django-CRUD-Atelier">
              <i class="fab fa-github"></i>
            </a>
          </li>

          

          <!-- Avatar -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle hidden-arrow d-flex align-items-center" href="#"
              id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
              <img src="https://img.icons8.com/color/50/000000/sewing-machine.png" class="rounded-circle" height="22"
                alt="" loading="lazy" />
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
              
              <li><a class="dropdown-item" href="#">{{request.user.username}}</a></li>
              <li><a class="dropdown-item" href="#">Tareas</a></li>
              <li><a class="dropdown-item" href="{% url 'core:logout' %}">Logout</a></li>
              
            </ul>
          </li>
        </ul>
      </div>
      <!-- Container wrapper -->
    </nav>
    
    <!-- Navbar -->
  </header> 
  
  <!--Main layout-->    
  <main style="margin-top: 58px">
    <div class="container pt-4">      
      
        {% block body%}
        {% endblock %}
    </div>
  </main>    
  {% endif %}      
 
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
    $(document).ready(function(){
      {% block jquery %}
      {% endblock jquery %}
    }) 
 
  </script>
</body>
</html>

templates/clients.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<section class="mb-4 ">
    <div class="col-lg-4 col-xl-4 offset-lg-4 col-md-6 offset-md-3 col-sm-12 pb-10">
    
        <div class="card">
            <div class='card-header text-center'><h2>Clientes</h2></div>
            <div class="card-body">
                <form  method="POST">{% csrf_token %}
                            {{ form|crispy }}
                    <div class="form-group pt-2">
                    <button type="submit" class="btn btn-success btn-block text-white " >Crear</button>
                    </div>
                </form>
            </div>
        </div>
           
    </div>
</section>

 
<section class="mb-4">
    <div class="card">
        <div class="card-header text-center py-3">
        <h5 class="mb-0 text-center"><strong>Tabla de clientes</strong></h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Direccion</th>
                                <th>Telefono</th>
                                <th colspan="2">Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for c in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><a href="{{ c.get_absolute_url }}" class="btn btn-info">{{c.name}}</a></td>
                                <td>{{c.adress}}</td>
                                <td>{{c.phone}}  {% if c.phone2 %}	<br> {{c.phone2}}  {% endif %}</td>
                                {% if c.isbad %} 
                                <td>Esta en la lista negra</td>
                                
                                {% endif %}
                                <td><a href="{{c.get_delete_client_url}}" class="btn btn-danger btnEliminacion">X</a></td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>  
{% endblock %}

templates/detail_client.html
{% extends "./base.html" %}

{% block title %} Gestión de Clientes {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Editar cliente : </h2><h2>{{object.name}}</h2>
        <div class="card">
            <div class="card-body">
                <form  method="POST">{% csrf_token %}{% load crispy_forms_tags %} {{ form|crispy }}
                 
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/detail_order.html
{% extends "./base.html" %}

{% block title %} Gestión de Clientes {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Editar orden #{{order.id}} :  </h2><h2></h2>
        <div class="card">
            <div class="card-body">
                <form  method="POST">{% csrf_token %}{% load crispy_forms_tags %} {{ form|crispy }}
                 
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/detail_service.html
{% extends "./base.html" %}

{% block title %} Gestión de Servicios {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Editar Servicio {{serv.name}} :  </h2><h2></h2>
        <div class="card">
            <div class="card-body">
                <form  method="POST">{% csrf_token %}{% load crispy_forms_tags %} {{ form|crispy }}
                 
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block f-right mt-4 text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/detail_task.html
{% extends "./base.html" %}

{% block title %} Gestión de Clientes {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4 text-center">
        <h2>Editar Tarea : </h2><h2></h2>
        <div class="card">
            <div class="card-body">
                <form  method="POST">{% csrf_token %}{% load crispy_forms_tags %} {{ form|crispy }}
                 
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/login.html

{% extends './base.html' %} {% load crispy_forms_tags %} {% block login %}
<div class="row justify-content-center pt-5">
  <div class="col-xl-4 col-lg-4 col-md-6 col-sm-10 align-self-center pt-5">
    <div class="card shadow-lg bg-white rounded">
      <div class="card-header bg-primary text-center text-white">
        <h1>Bienvenido a <br />Morando's Atelier</h1>
      </div>
      <div class="card-body">
        <form action="" method="post">
          {% csrf_token %} {{ form|crispy }}
          <div class="form-group">
            <button
              type="submit"
              class="btn btn-success btn-block text-white f-right mt-4"
            >
              Entrar
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock login %}

templates/months.html
{% extends './base.html' %} {% load humanize %} {% block body %}

  


  
<section>  
  
<div class="container mb-4">
  
    <div class="col "><h1>Listado de Pedidos de {{month|date:"F "}}</h1>
    </div>
        <div class="btn-group  col-sm-2" role="group" aria-label="Basic example">
        {% if previous_month %}
            
        <a href='{% url 'core:orders-month' previous_month|date:'Y' previous_month|date:'m' %}' class="button btn btn-primary">{{ previous_month|date:'F' }}
        </a>

        {% endif %}
        
        <a  class="button btn btn-outline-primary"=>{{month|date:"F"}}</a>
        {% if next_month %}
        <a href='{% url 'core:orders-month' next_month|date:'Y' next_month|date:'m' %}'  class="button btn  btn-primary"  >{{ next_month|date:'F' }}</a>  
            {% endif %}
        </div> 
</div>
</section>  
<section>
<div class="container">
  <div class="row">
    <div class="col-xl-6 col-md-12 mb-4">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between p-md-1">
                <div class="d-flex flex-row">
                    <div class="align-self-center">
                    <i class="fas fa-wallet text-info fa-3x me-4"></i>
                    </div>
                    <div>
                    <h4>Ingreso bruto </h4>
                    <p class="mb-0">{{month|date:" F Y "}}</p>
                    </div>
                </div>
                <div class="align-self-center">
                    <h2 class="h1 mb-0"> {% if money_m %} {{money_m|intword}}$ {% else %}<i class="fas fa-grin-beam-sweat text-info "></i> {% endif %} </h2>
                </div>
                </div>
            </div>
            </div>
        </div>
        <div class="col-xl-6 col-md-12 mb-4">
            <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between p-md-1">
                <div class="d-flex flex-row">
                    <div class="align-self-center">
                    <i class="fas fa-pencil-alt text-warning fa-3x me-4"></i>
                    </div>
                    <div>
                    <h4>Total de ordenes</h4>
                    <p class="mb-0">{{month|date:"F Y "}}</p>
                    </div>
                </div>
                <div class="align-self-center">
                    <h2 class="h1 mb-0"> {{ count|intword }}</h2>
                </div>
                </div>
            </div>
            </div>
        </div>
        <div class="col-xl-6 col-md-12 mb-4">
            <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between p-md-1">
                <div class="d-flex flex-row">
                    <div class="align-self-center">
                    <i class="fas fa-smile-beam text-success fa-3x me-4"></i>
                    </div>
                    <div>
                    <h4>Ordenes Completadas</h4>
                    <p class="mb-0">{{month|date:"F Y "}}</p>
                    </div>
                </div>
                <div class="align-self-center">
                    <h2 class="h1 mb-0"> {{ count_m|intword }}</h2>
                </div>
                </div>
            </div>
            </div>
        </div>
        <div class="col-xl-6 col-md-12 mb-4">
            <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between p-md-1">
                <div class="d-flex flex-row">
                    <div class="align-self-center">
                    <i class="fas fa-angry text-danger fa-3x me-4"></i>
                    </div>
                    <div>
                    <h4>Ordenes Pendientes</h4>
                    <p class="mb-0">{{month|date:"F Y "}}</p>
                    </div>
                </div>
                <div class="align-self-center">
                    <h2 class="h1 mb-0"> {{ count_p|intword }}</h2>
                </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
</section>

<section>
<div class="container">
  <div class="row">
   
    {% for c in object_list %}
    <div class="col-xl-3 col-sm-6 col-12 mb-4">
        <div class="card">
          <div class="card-body">
            <div class="d-flex justify-content-between px-md-1">
              <div class="align-self-center">
                {% if not c.paid   %}<a href="{% url 'core:ispaidbydate' c.id month|date:'Y' month|date:'m' %}"><i class="fas fa-business-time text-danger fa-3x"></i></a>{% else %}<a href="{% url 'core:detail-order' c.pk %}"> <i class="fa fa-cart-plus text-success fa-3x"></i></a>{% endif %}
                
              </div>
              <div class="text-end">
                <h3>{{c.get_final_price|intword}} $</h3>
                <p class="mb-0">{{c.client}}{% with c.service.all.count as service %}<span class="badge badge-pill badge-danger text-danger">{{service}} serv</span>{% endwith %} <br> {{c.start_date|naturaltime}}</p>
              </div>
            </div>
          </div>
        </div>
    </div>
   

    {% endfor %}
</section>
<section class="mb-4">
    <div class="card">
      <div class="card-header text-center py-3">
        <h5 class="mb-0 text-center"><strong>Resumen de {{month|date:" F Y "}} </strong></h5>
      </div>
      <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover text-nowrap">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th class="text-center" scope="col">Cliente</th>
                    <th class="text-center" scope="col">Servicios</th>
                    <th class="text-center" scope="col">Extra (CUP)</th>
                    <th class="text-center" scope="col">Duración (Días)</th>
                    <th class="text-center" scope="col">Entregado</th>
                    
                    <th class="text-center" scope="col">Ganancia (CUP) </th>
                </tr>
                </thead>
                <tbody>
                {% for order_item in object_list %}
                {% if order_item.paid %}
                <tr>
                    <th scope="row">{{ order_item.id }}</th>
                    <td class="text-center">{{ order_item.client }}</td>
                    <td class="text-center" >
                        
                        {% for d in order_item.service.all %}
                        {% if forloop.last %}
                        {{d}}.
                        {% elif forloop.counter == 4 or forloop.counter == 7 %} <br> 
                        {{d}},
                        {% else %}
                        {{d}}, 
                        {% endif %}
                        {% endfor %}
                        
                    </td>
                    <td class="text-center">{% if order_item.extra_price %}{{ order_item.extra_price|intword }} {% else %} -- {% endif %}</td>
                    <td class="text-center">{{order_item.get_delivery_time|naturaltime}}</td>
                    <td class="text-center">{{order_item.order_date|date:" d/n/y "}}</td>
                    <td class="text-center">{{ order_item.get_final_price|intword }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                {% if not money_m %}  <tr>
                    <th class="text-center" scope="col">Este mes todavia no has ganado dinerito <i class="fas fa-grin-beam-sweat  "></i> Que pasa?</th>
                </tr> {% endif %}
               
                
                
               
            
                </tbody>
            </table>
        </div>
    </div>
</section>

  {% endblock %}

templates/order.html
{% extends './base.html' %} {% load crispy_forms_tags %} {% block body %} 


<section class="mb-4 ">
  <div class="col-lg-4 col-xl-4 offset-lg-4 col-md-6 offset-md-3 col-sm-12 pb-10">
  
      <div class="card">
          <div class='card-header text-center'><h2>Ordenes</h2></div>
          <div class="card-body">
              <form  method="POST">{% csrf_token %}
                          {{ form|crispy }}
                  <div class="form-group pt-2">
                  <button type="submit" class="btn btn-success btn-block text-white " >Crear</button>
                  </div>
              </form>
          </div>
      </div>
         
  </div>
</section>
  
<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center"><strong>Tabla de Ordenes
        
      </strong></h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover text-nowrap">
              <thead>
                <tr>
                  <th>#</th>
                  <th class="text-center">Cliente</th>
                  <th class="text-center">Fecha</th>
                  <th class="text-center">Servicio</th>
                  <th class="text-center">Total</th>
                  
                  <th class="text-center">Pagado</th>
                  <th class="text-center">Opciones</th>
                </tr>
              </thead>
              <tbody>
                {% for c in object_list %}
                <tr>
                  <td >{{ forloop.counter }}</td>
                  <td class="text-center">{{c.client}}</td>
                  <td class="text-center">{{c.order_date|date:"d/n/y"}}</td>
                  <td style="width:100px" class="text-center" >
                        
                    {% for d in c.service.all %}
                    {% if forloop.last %}
                    {{d}}.
                    {% elif forloop.counter == 4 or forloop.counter == 7 %} <br> 
                    {{d}},
                    {% else %}
                    {{d}}, 
                    {% endif %}
                    {% endfor %}
                    
                </td>
                  <td class="text-center">{{c.get_final_price}} $</td>
                  
                  <td class="text-center">{% if c.paid %} <i class="fas fa-check fa-2x"></i>{% else %}<a href="{% url 'core:ispaid' c.pk %}"><i class="fas fa-times-circle fa-2x "></i></a> {% endif %}</td>
                  
                  <td class="text-center">
                    <a href="{% url 'core:detail-order' c.pk %}" class="btn btn-info">+</a>
                   
                    
                    <a href="{% url 'core:del-order' c.pk %}" class="btn btn-danger">x</a>
                   
                  </td>
                </tr>
                {% endfor %}
              </tbody>
        </table>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/serv_check_del.html

{% extends './base.html' %} {% load crispy_forms_tags %} 


{% block body %}

<section class="mb-4 ">
  <div class="col-lg-4 col-xl-4 offset-lg-4 col-md-6 offset-md-3 col-sm-12 pb-10">
  
      <div class="card">
          <div class='card-header text-center'><h2>Seguro quieres eliminar este servicio?</h2></div>
          <div class="card-body">
            <p class="text-primary"><small>Si lo eliminas se descontara su precio a todas las ordenes que contengan este servicio.</small></p>
              <form  method="POST">{% csrf_token %}
                          {{ form|crispy }}
                <div class="form-group pt-2" style="float: right;">
                    <a type="button" href='{% url 'core:services' %}' class="btn btn-danger  text-white "  >Cancelar</a>
                    <button type="submit" class="btn btn-primary  text-white " >Eliminar</button>
                </div>
              </form>
          </div>
      </div>
         
  </div>


       
    
{% endblock body %}

templates/services.html
{% extends "./base.html" %} {% load crispy_forms_tags %}



{% block title %} Gestión de Servicios {% endblock title %}

{% block body %}
<section class="mb-4 ">
<div class="col-lg-4 col-xl-4 offset-lg-4 col-md-6 offset-md-3 col-sm-12 pb-10">

    <div class="card">
        <div class='card-header text-center'><h2>Servicios</h2></div>
        <div class="card-body">
            <form action="{% url 'core:services' %}" method="POST">{% csrf_token %}
                        {{ form|crispy }}
                <div class="form-group pt-2">
                <button type="submit" class="btn btn-success btn-block text-white " >Crear</button>
                </div>
            </form>
        </div>
    </div>
       
</div>
</section>
<section class="mb-4 ">
    <div class="row">
{% regroup object_list by get_section_display as country_list %}
{% for country in country_list %}

    <div class="col-xl-6">
    <div class="card ">
      <div class="card-header text-center py-3">
        <h5 class="mb-0 text-center">
          <strong>{{ country.grouper }}</strong>
        </h5>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                
                <th scope="row">Servicio</th>
                <th scope="row">Precio</th>
                <th scope="row" class='f-right'colspan="2">Opciones</th>
              </tr>
            </thead>
            <tbody>
                {% for c in country.list %}
                <tr> 
                    
                    <td><a href="{{ c.get_absolute_url }}" class="btn btn-info">{{c.name}}</a></td>
                    <td>{{c.price}}</td>
                    
                    <td><a href="{{c.get_add_to_cart_url}}" class="btn btn-success btnEliminacion">+</a>
                            <a href="{% url 'core:del-serv' c.pk %}" class="btn btn-danger btnEliminacion">X</a></td>
                   
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
</div> 
{% endfor %}
</div>
</section>








{% endblock body %}

templates/task_check_delete.html

{% extends './base.html' %} {% load crispy_forms_tags %} 


{% block body %}

<section class="mb-4 ">
  <div class="col-lg-4 col-xl-4 offset-lg-4 col-md-6 offset-md-3 col-sm-12 pb-10">
  
      <div class="card">
          <div class='card-header text-center'><h2>Seguro quieres eliminar esta tarea?</h2></div>
          <div class="card-body">
            
              <form  method="POST">{% csrf_token %}
                          {{ form|crispy }}
                <div class="form-group pt-2" style="float: right;">
                    <a type="button" href='{% url 'core:task' %}' class="btn btn-danger  text-white "  >Cancelar</a>
                    <button type="submit" class="btn btn-primary  text-white " >Eliminar</button>
                </div>
              </form>
          </div>
      </div>
         
  </div>


       
    
{% endblock body %}